/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library mtproj.mt_api.file_type;

class FileType {
  static const int DIRECTORY = 0;
  static const int DOCUMENT = 1;

  static final Set<int> VALID_VALUES = new Set.from([
    DIRECTORY
    , DOCUMENT
  ]);
  static final Map<int, String> VALUES_TO_NAMES = {
    DIRECTORY: 'DIRECTORY'
    , DOCUMENT: 'DOCUMENT'
  };
}
